#!/bin/sh

wiiload "$1"
# empiric value, no idea if this differs for large executables
echo Starting in 4...
sleep 1
echo 3...
sleep 1
echo 2...
sleep 1
echo 1...
sleep 1
echo Connecting...
netcat ${WIILOAD#tcp:} 16784
